Repository jupyterhub/jupyterhub, pull requests merged in 2020-12, with the labels that each got.

#3244 [Docs] Fix https reverse proxy redirect issues
  docs/source/reference/config-proxy.md
Labels: documentation

#3225 Allow options_from_form to be configurable
  jupyterhub/spawner.py
Labels: enhancement

#3243 [Metrics] Add prefix to prometheus metrics to group all jupyterhub metrics
  jupyterhub/metrics.py
Labels: enhancement

#3294 fix increasing pagination limits
  jupyterhub/handlers/pages.py
  jupyterhub/pagination.py
  jupyterhub/tests/test_pagination.py
Labels: bug

#3293 allow services to call /api/user to identify themselves
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/test_api.py
Labels: enhancement
