Repository jupyterhub/jupyterhub, pull requests merged in 2020-11, with the labels that each got.

#3246 Migrate from travis to GitHub actions
  .github/workflows/test.yml
  .travis.yml
  ci/docker-db.sh
  ci/init-db.sh
Labels: maintenance

#3253 wait for pending spawns in spawn_form_admin_access
  jupyterhub/tests/test_pages.py
Labels: maintenance

#3176 Enable async support in jinja2 templates
  jupyterhub/apihandlers/auth.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/login.py
  jupyterhub/handlers/pages.py
  setup.py
Labels: enhancement

#3169 First step for implementing oauth scopes - update to rest-api.yml
  docs/rest-api.yml
Labels: enhancement

#3242 Assume py36 and remove @gen.coroutine etc.
  .github/workflows/test.yml
  .gitignore
  docs/source/reference/authenticators.md
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/proxy.py
  jupyterhub/services/auth.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/spawner.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_internal_ssl_connections.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_services.py
  jupyterhub/tests/test_spawner.py
  jupyterhub/tests/test_utils.py
  jupyterhub/utils.py
  requirements.txt
Labels: maintenance

#3237 [proxy.py] Improve robustness when detecting and closing existing proxy processes
  jupyterhub/proxy.py
Labels: bug, needs: discussion

#3261 Only preserve params when ?next= is unspecified
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/tests/test_pages.py
Labels: bug

#3177 add ?state= filter for GET /users
  docs/rest-api.yml
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/test_api.py
Labels: enhancement
