Repository jupyterhub/jupyterhub, pull requests merged in 2021-12, with the labels that each got.

#3195 add option to use a different Host header for referer checks
  jupyterhub/apihandlers/base.py
  jupyterhub/app.py
  jupyterhub/tests/test_api.py
Labels: enhancement

#3698 run jsx tests in their own job
  .github/workflows/test.yml
Labels: maintenance, ci

#3701 cors: handle mismatched implicit/explicit ports in host header
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/test_api.py
Labels: bug

#3697 React Error Handling
  jsx/package.json
  jsx/src/components/AddUser/AddUser.jsx
  jsx/src/components/AddUser/AddUser.test.js
  jsx/src/components/CreateGroup/CreateGroup.jsx
  jsx/src/components/CreateGroup/CreateGroup.test.js
  jsx/src/components/EditUser/EditUser.jsx
  jsx/src/components/EditUser/EditUser.test.js
  jsx/src/components/GroupEdit/GroupEdit.jsx
  jsx/src/components/GroupEdit/GroupEdit.test.jsx
  jsx/src/components/GroupSelect/GroupSelect.jsx
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/util/withAPI.js
  jsx/yarn.lock
  share/jupyterhub/static/js/admin-react.js
Labels: enhancement

#3719 check for db clients before requesting install
  .github/workflows/test.yml
Labels: maintenance

#3717 fix Spawner.oauth_roles config
  jupyterhub/tests/test_spawner.py
  jupyterhub/user.py
Labels: bug

#3714 Grant role after user creation during config load
  jupyterhub/app.py
  jupyterhub/tests/test_app.py
  jupyterhub/tests/test_roles.py
Labels: bug

#3716 Fix error message about Authenticator.pre_spawn_start
  jupyterhub/handlers/pages.py
  jupyterhub/tests/test_pages.py
Labels: bug

#3720 simplify default role assignment
  jupyterhub/roles.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_roles.py
Labels: bug

#3705 use intersect_scopes utility to check token permissions
  jupyterhub/roles.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_scopes.py
  jupyterhub/tests/test_services_auth.py
Labels: enhancement

#3708 Avoid clearing user role membership when defining custom user scopes
  jupyterhub/app.py
  jupyterhub/roles.py
  jupyterhub/tests/test_roles.py
Labels: bug

#3727 clarify `role` argument in grant/strip_role
  jupyterhub/roles.py
Labels: maintenance

#3722 always assign default roles on login
  jupyterhub/handlers/base.py
  jupyterhub/tests/test_roles.py
Labels: enhancement

#3731 accept token auth on `/hub/user/...`
  jupyterhub/handlers/base.py
Labels: bug

#3733 Fix missing f-string modifier
  jupyterhub/apihandlers/base.py
Labels: bug

#3726 update service-whoami example
  examples/service-whoami/README.md
  examples/service-whoami/jupyterhub_config.py
Labels: documentation

#3735 initialize new admin users with default roles
  jupyterhub/app.py
  jupyterhub/tests/test_api.py
Labels: bug

#3723 Use URL from authenticator on default login form
  share/jupyterhub/templates/login.html
Labels: enhancement
