Repository jupyterhub/jupyterhub, pull requests merged in 2021-04, with the labels that each got.

#3415 Changelog for 1.4
  docs/source/changelog.md
Labels: documentation

#3417 Fix link to jupyterhub/jupyterhub-the-hard-way
  docs/source/installation-guide-hard.rst
Labels: documentation

#3430 Support Proxy.extra_routes
  jupyterhub/proxy.py
  jupyterhub/tests/test_proxy.py
Labels: new

#3424 more changelog for 1.4
  docs/source/changelog.md
Labels: documentation

#3436 ci: github workflow security, pin action to sha etc
  .github/workflows/release.yml
Labels: ci
