Repository jupyterhub/jupyterhub, pull requests merged in 2021-05, with the labels that each got.

#3452 Fix documentation
  docs/source/getting-started/authenticators-users-basics.md
  docs/source/getting-started/config-basics.md
  docs/source/getting-started/faq.md
  docs/source/getting-started/institutional-faq.md
  docs/source/getting-started/networking-basics.md
  docs/source/getting-started/services-basics.md
  docs/source/getting-started/spawners-basics.md
Labels: documentation

#3437 patch base handlers from both jupyter_server and notebook
  jupyterhub/singleuser/mixins.py
Labels: enhancement

#3456 avoid re-using asyncio.Locks across event loops
  jupyterhub/proxy.py
Labels: maintenance

#3454 define Spawner.delete_forever on base Spawner
  jupyterhub/apihandlers/users.py
  jupyterhub/spawner.py
  jupyterhub/tests/mocking.py
  jupyterhub/user.py
Labels: maintenance

#3457 ci: fix typo in environment variable
  .github/workflows/release.yml
Labels: ci
