Repository jupyterhub/jupyterhub, pull requests merged in 2021-08, with the labels that each got.

#3539 Update changelog for 1.4.2 in main branch
  README.md
  docs/source/changelog.md
Labels: documentation

#3562 remove use of deprecated distutils
  jupyterhub/_version.py
  requirements.txt
  setup.py
Labels: maintenance

#3561 remove old, unused tasks.py
  tools/tasks.py
Labels: maintenance

#3559 support inherited `--show-config` flags from base Application
  jupyterhub/app.py
  jupyterhub/tests/test_app.py
Labels: new

#3569 Fix wrong name of auth_state_hook in the exception log
  jupyterhub/spawner.py
Labels: bug

#3568 Stop injecting statsd parameters into the configurable HTTP proxy
  jupyterhub/proxy.py
Labels: bug

#3558 remove very old backward-compat for LocalProcess subclasses
  jupyterhub/spawner.py
Labels: maintenance

#3565 Add detailed doc for starting/waiting for servers via api
  .gitignore
  docs/source/conf.py
  docs/source/reference/index.rst
  docs/source/reference/server-api.md
  examples/server-api/jupyterhub_config.py
  examples/server-api/start-stop-server.py
Labels: documentation
