Repository jupyterhub/jupyterhub, pull requests merged in 2021-01, with the labels that each got.

#3324 ci: github actions, allow for manual test runs and fix badge in readme
  .github/workflows/test.yml
  README.md
Labels: maintenance

#3325 Fix mixup in comment regarding the sync parameter
  jupyterhub/handlers/base.py
Labels: documentation

#3343 Allow cookie_secret to be set to a hexadecimal string
  jupyterhub/app.py
  jupyterhub/tests/test_app.py
Labels: enhancement
