Repository jupyterhub/jupyterhub, pull requests merged in 2022-01, with the labels that each got.

#3747 localhost URL is http, not https
  README.md
Labels: documentation

#3748 DOC: Add note about allowed_users not being set
  docs/source/getting-started/authenticators-users-basics.md
Labels: documentation

#3750 ci: refactor to avoid triggering all tests on changes to docs
  .github/workflows/release.yml
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
  docs/requirements.txt
  docs/source/rbac/generate-scope-table.py
  docs/test_docs.py
Labels: maintenance, ci

#3760 remove unused macro with missing references
  share/jupyterhub/templates/admin.html
Labels: maintenance

#3759 changelog for 2.0.2
  docs/source/changelog.md
Labels: documentation

#3764 relay custom messages in exception.jupyterhub_message in progress API
  jupyterhub/apihandlers/users.py
  jupyterhub/handlers/pages.py
  share/jupyterhub/templates/not_running.html
Labels: enhancement

#3765 Improve documentation about spawner exception handling
  docs/source/reference/spawners.md
Labels: documentation

#3763 apply scope checks to some admin-or-self situations
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/tests/test_pages.py
Labels: bug

#3775 DOCS: Add github metadata for edit button
  docs/source/conf.py
Labels: maintenance

#3773 Using orm_spawner in server model user_options
  jupyterhub/tests/test_spawner.py
  jupyterhub/user.py
Labels: bug

#3548 Authenticator user group management
  docs/source/reference/authenticators.md
  examples/azuread-with-group-management/jupyterhub_config.py
  examples/azuread-with-group-management/requirements.txt
  jupyterhub/apihandlers/groups.py
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/handlers/base.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_auth.py
  jupyterhub/tests/test_user.py
  jupyterhub/user.py
Labels: new

#3781 Log proxy's public_url only when started by JupyterHub
  jupyterhub/app.py
Labels: bug
