Repository jupyterhub/jupyterhub, pull requests merged in 2022-04, with the labels that each got.

#3859 Do not store Spawner.ip/port on spawner.server during get_env
  jupyterhub/spawner.py
Labels: bug

#3867 ci: update black configuration
  .pre-commit-config.yaml
  pyproject.toml
Labels: ci

#3851 !service and !server filters
  docs/source/rbac/scopes.md
  jupyterhub/oauth/provider.py
  jupyterhub/orm.py
  jupyterhub/scopes.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_scopes.py
Labels: new

#3876 don't confuse :// in next_url query params for a redirect hostname
  jupyterhub/handlers/base.py
  jupyterhub/tests/test_pages.py
Labels: bug
