Repository jupyterhub/jupyterhub, pull requests merged in 2022-05, with the labels that each got.

#3886 Cleanup everything on API shutdown
  jupyterhub/apihandlers/hub.py
  jupyterhub/app.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_api.py
Labels: bug

#3887 2.3 backports
  .pre-commit-config.yaml
  README.md
  dev-requirements.txt
  docs/source/admin/log-messages.md
  docs/source/changelog.md
  docs/source/rbac/roles.md
  docs/source/rbac/scopes.md
  docs/source/rbac/upgrade.md
  jsx/build/admin-react.js.LICENSE.txt
  jsx/package.json
  jsx/src/Store.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/util/withAPI.js
  jsx/yarn.lock
  jupyterhub/apihandlers/groups.py
  jupyterhub/apihandlers/hub.py
  jupyterhub/apihandlers/users.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/spawner.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_app.py
  jupyterhub/tests/test_pages.py
  jupyterhub/user.py
  pyproject.toml
  pytest.ini
  share/jupyterhub/static/js/admin-react.js
Labels: maintenance

#3889 admin: make user-info table selectable
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  share/jupyterhub/static/js/admin-react.js
Labels: bug

#3891 remove apache NE flag as it prevents opening folders and renaming fil…
  docs/source/reference/config-proxy.md
Labels: documentation

#3885 Deprecate Authenticator.db, Spawner.db
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/spawner.py
  jupyterhub/user.py
Labels: api-change

#3903 `jupyter troubleshooting` ➡️ `jupyter troubleshoot`
  docs/source/troubleshooting.md
Labels: documentation

#3906 Force add existing certificates
  jupyterhub/app.py
Labels: bug

#3908 allow auth_state_hook to halt spawn
  jupyterhub/spawner.py
Labels: bug

#3915 Update Contributing documentation
  CONTRIBUTING.md
  docs/source/contributing/setup.rst
  docs/source/contributing/tests.rst
Labels: documentation
