Repository jupyterhub/jupyterhub, pull requests merged in 2022-11, with the labels that each got.

#4139 highlight note about the docker image scope
  docs/source/quickstart-docker.rst
Labels: documentation, needs: upstream action, outreachy-dec22

#4187 ci: use non-deprecated codecov uploader
  .github/workflows/test.yml
  dev-requirements.txt
Labels: ci

#4204 [docs] typo in access:servers scope
  docs/source/reference/rest.md
  docs/source/reference/services.md
Labels: documentation

#4208 improved the grammatical structure
  docs/source/contributing/docs.rst
Labels: documentation

#4216 ci: flake8, cleanup unused/redundant config
  .flake8
Labels: maintenance, ci

#4222 docs: sphinx config cleanup, removing epub build, fix build warnings
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/admin/upgrading.rst
  docs/source/conf.py
  docs/source/getting-started/config-basics.md
  docs/source/reference/config-sudo.md
Labels: documentation

#4225 selenium: update next_url after waiting for it to change
  jupyterhub/tests/selenium/test_browser.py
Labels: maintenance

#4223 maint: add test to extras_require, remove greenlet workaround, test final py311, misc cleanup
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
  .readthedocs.yaml
  RELEASE.md
  ci/mock-greenlet/greenlet.py
  ci/mock-greenlet/pyproject.toml
  dev-requirements.txt
  docs/requirements.txt
  docs/source/conf.py
  docs/source/contributing/setup.rst
  docs/source/contributing/tests.rst
  setup.py
Labels: maintenance

#4227 docs: refresh conf.py, add opengraph and rediraffe extensions
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
  docs/source/contributing/tests.rst
Labels: documentation

#4210 grammar in security-basics.rst
  docs/source/getting-started/security-basics.rst
Labels: documentation, outreachy-dec22

#2641 Some suggestions from reading through the docs
  README.md
  docs/source/contributing/docs.rst
  docs/source/contributing/setup.rst
  docs/source/contributing/tests.rst
  docs/source/getting-started/networking-basics.md
  docs/source/getting-started/security-basics.rst
  docs/source/getting-started/services-basics.md
  docs/source/quickstart-docker.rst
  docs/source/reference/authenticators.md
  docs/source/reference/config-proxy.md
  docs/source/reference/config-sudo.md
  docs/source/reference/config-user-env.md
  docs/source/reference/proxy.md
  docs/source/reference/separate-proxy.md
  docs/source/reference/services.md
  docs/source/reference/spawners.md
  docs/source/reference/urls.md
Labels: documentation

#4094 Fixed typos and added punctuations
  docs/source/admin/upgrading.rst
  docs/source/getting-started/security-basics.rst
Labels: documentation, outreachy-dec22

#4119 Formatting changes to tests.rst
  docs/source/contributing/tests.rst
Labels: documentation, outreachy-dec22

#4186 highlight "what is our actual goal" in faq
  docs/source/getting-started/faq.md
Labels: documentation, outreachy-dec22

#4084 Refine text in documentation index
  docs/source/index.rst
Labels: documentation, outreachy-dec22

#4072 [doc] templates: updated obsolete links and made wordings clearer
  docs/source/reference/templates.md
Labels: needs: upstream action, outreachy-dec22

#4136 Update wording in web security docs
  docs/source/reference/websecurity.md
Labels: documentation, outreachy-dec22

#4130 refine text in template docs.
  docs/source/reference/templates.md
Labels: documentation, outreachy-dec22

#4172 Deleted unused failRegexEvent
  jsx/src/components/AddUser/AddUser.jsx
  jsx/src/components/AddUser/AddUser.test.js
  jsx/src/components/CreateGroup/CreateGroup.jsx
  jsx/src/components/EditUser/EditUser.jsx
  jsx/src/components/EditUser/EditUser.test.js
  jsx/src/util/withAPI.js
Labels: maintenance, outreachy-dec22

#4185 Edits to institutional FAQ
  docs/source/getting-started/institutional-faq.md
Labels: documentation, outreachy-dec22

#4150 grammar improvements in quickstart.md
  docs/source/quickstart.md
Labels: documentation, outreachy-dec22

#4008 Add draft capacity planning doc
  docs/source/admin/capacity-planning.md
  docs/source/images/mybinder-hub-components-cpu-memory.png
  docs/source/images/mybinder-load5.png
  docs/source/images/mybinder-user-resources.png
  docs/source/index-admin.rst
Labels: documentation

#4156 Update dockerfile README
  dockerfiles/README.md
Labels: documentation, outreachy-dec22

#4127 update troubleshooting.md docs
  docs/source/troubleshooting.md
Labels: documentation, outreachy-dec22

#4230 make current_user available to handle_logout hook
  jupyterhub/handlers/base.py
  jupyterhub/handlers/login.py
  jupyterhub/tests/test_pages.py
Labels: bug
