Repository jupyterhub/jupyterhub, pull requests merged in 2022-08, with the labels that each got.

#3997 Remove outdated cookie-secret note in security docs
  docs/source/getting-started/security-basics.rst
Labels: documentation

#3992 Avoid IOLoop.current in singleuser mixins
  jupyterhub/app.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/mocking.py
Labels: maintenance

#4000 [admin] update, clean jsx deps
  jsx/package.json
  jsx/webpack.config.js
  jsx/yarn.lock
Labels: maintenance

#3877 store scopes on oauth clients, too
  docs/source/_static/rest-api.yml
  docs/source/rbac/scopes.md
  docs/source/reference/services.md
  docs/source/reference/spawners.md
  examples/custom-scopes/jupyterhub_config.py
  examples/service-whoami/README.md
  examples/service-whoami/jupyterhub_config.py
  jupyterhub/alembic/versions/651f5419b74d_api_token_scopes.py
  jupyterhub/app.py
  jupyterhub/oauth/provider.py
  jupyterhub/orm.py
  jupyterhub/services/auth.py
  jupyterhub/services/service.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_services.py
  jupyterhub/tests/test_services_auth.py
  jupyterhub/tests/test_spawner.py
  jupyterhub/user.py
Labels: new

#3909 include stopped servers in user model
  docs/source/_static/rest-api.yml
  jsx/src/App.jsx
  jsx/src/util/withAPI.js
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/test_named_servers.py
Labels: new

#4011 restore trimming of username input
  jupyterhub/auth.py
  jupyterhub/handlers/login.py
  jupyterhub/tests/test_pages.py
Labels: bug

#4012 document oauth_no_confirm in services
  docs/source/reference/services.md
Labels: documentation

#4013 Test 3.11
  .github/workflows/test.yml
  ci/mock-greenlet/greenlet.py
  ci/mock-greenlet/pyproject.toml
Labels: maintenance, ci

#4019 avoid database error on repeated group name in sync_groups
  jupyterhub/tests/test_user.py
  jupyterhub/user.py
Labels: bug

#4022 Use correct expiration labels in drop-down menu on token page.
  share/jupyterhub/templates/token.html
Labels: bug
