Repository jupyterhub/jupyterhub, pull requests merged in 2022-12, with the labels that each got.

#4209 avoid contraction in setup.rst
  docs/source/contributing/setup.rst
Labels: documentation, outreachy-dec22

#4236 deprecate JupyterHub.extra_handlers
  jupyterhub/app.py
Labels: api-change

#4214 Add active users prometheus metrics
  jupyterhub/app.py
  jupyterhub/metrics.py
  jupyterhub/tests/test_metrics.py
Labels: new

#4234 changelog for 1.5.1
  .pre-commit-config.yaml
  docs/source/changelog.md
Labels: documentation

#4232 changelog for 3.1.0
  docs/source/changelog.md
Labels: documentation

#4248 maint: fix detail when removing support for py36
  .pre-commit-config.yaml
Labels: maintenance

#4250 fix bracket typo in capacity figures
  docs/source/admin/capacity-planning.md
Labels: documentation

#4249 convert remaining rst files to myst
  docs/generate-metrics.py
  docs/source/admin/upgrading.md
  docs/source/admin/upgrading.rst
  docs/source/api/app.md
  docs/source/api/app.rst
  docs/source/api/auth.md
  docs/source/api/auth.rst
  docs/source/api/index.md
  docs/source/api/index.rst
  docs/source/api/proxy.md
  docs/source/api/proxy.rst
  docs/source/api/service.md
  docs/source/api/service.rst
  docs/source/api/services.auth.md
  docs/source/api/services.auth.rst
  docs/source/api/spawner.md
  docs/source/api/spawner.rst
  docs/source/api/user.md
  docs/source/api/user.rst
  docs/source/conf.py
  docs/source/contributing/docs.md
  docs/source/contributing/docs.rst
  docs/source/contributing/index.md
  docs/source/contributing/index.rst
  docs/source/contributing/security.md
  docs/source/contributing/security.rst
  docs/source/contributing/setup.md
  docs/source/contributing/setup.rst
  docs/source/contributing/tests.md
  docs/source/contributing/tests.rst
  docs/source/events/index.md
  docs/source/events/index.rst
  docs/source/events/server-actions.md
  docs/source/getting-started/config-basics.md
  docs/source/getting-started/index.md
  docs/source/getting-started/security-basics.md
  docs/source/getting-started/security-basics.rst
  docs/source/index-about.md
  docs/source/index-admin.md
  docs/source/index-admin.rst
  docs/source/index.md
  docs/source/index.rst
  docs/source/installation-guide-hard.md
  docs/source/installation-guide-hard.rst
  docs/source/installation-guide.md
  docs/source/quickstart-docker.md
  docs/source/quickstart-docker.rst
  docs/source/rbac/scopes.md
  docs/source/rbac/upgrade.md
  docs/source/rbac/use-cases.md
  docs/source/reference/config-reference.md
  docs/source/reference/config-reference.rst
  docs/source/reference/index.md
  docs/source/reference/index.rst
  docs/source/reference/monitoring.md
  docs/source/reference/monitoring.rst
  docs/source/reference/technical-overview.md
Labels: documentation

#4256 docs: refresh Makefile/make.bat
  docs/Makefile
  docs/make.bat
  docs/source/contributing/docs.md
Labels: maintenance

#4264 remove unnecessary actions for firefox/geckodriver
  .github/workflows/test.yml
Labels: maintenance

#4259 set max depth on api/index toctree
  docs/source/api/index.md
Labels: documentation

#4271 only run testing config on localhost
  testing/jupyterhub_config.py
Labels: maintenance

#4269 Document JUPYTER_PREFER_ENV_PATH=0 for shared user environments
  docs/source/reference/config-user-env.md
Labels: documentation

#4268 pre-commit: autoupdate monthly
  .pre-commit-config.yaml
Labels: maintenance

#4245 doc: fix formatting of spawner env-vars
  docs/source/reference/spawners.md
Labels: documentation

#4278 Refactored selenium tests for improved readability
  jupyterhub/tests/selenium/locators.py
  jupyterhub/tests/selenium/test_browser.py
Labels: maintenance

#4258 Remove remnants of unused jupyterhub-services cookie
  examples/service-fastapi/README.md
  jupyterhub/app.py
  jupyterhub/handlers/base.py
Labels: bug
