Repository jupyterhub/jupyterhub, pull requests merged in 2022-06, with the labels that each got.

#3918 set default_url via config
  jupyterhub/singleuser/mixins.py
Labels: bug

#3914 Build admin app in setup.py
  .github/workflows/release.yml
  .github/workflows/test-jsx.yml
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  MANIFEST.in
  ci/check_installed_data.py
  ci/check_sdist.py
  jsx/build/admin-react.js.LICENSE.txt
  jsx/build/index.html
  jsx/package.json
  setup.py
  share/jupyterhub/static/js/admin-react.js
Labels: maintenance, ci

#3904 Escape named server name
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/users.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/proxy.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_named_servers.py
  jupyterhub/user.py
  jupyterhub/utils.py
Labels: bug

#3923 Backport PR #3837 on branch 2.x (ensure _import_error is set when JUPYTERHUB_SINGLEUSER_APP is unavailable)
  jupyterhub/singleuser/app.py
Labels: bug

#3924 Backport PR #3889 on branch 2.x (admin: make user-info table selectable)
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  share/jupyterhub/static/js/admin-react.js
Labels: bug

#3927 Backport PR #3918 on branch 2.x (set default_url via config)
  jupyterhub/singleuser/mixins.py
Labels: bug

#3931 Add changelog for 2.3.0 and 2.3.1
  docs/source/changelog.md
Labels: documentation

#3935 admin: Fix spawn page link for default server
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/util/jhapiUtil.js
  share/jupyterhub/templates/admin.html
Labels: bug

#3937 switch to importlib_metadata for entrypoints
  jupyterhub/traitlets.py
  requirements.txt
Labels: maintenance

#3939 chore: Set permissions for GitHub actions
  .github/workflows/test-jsx.yml
  .github/workflows/test.yml
Labels: ci

#3940 chore: add dependabot config for github actions
  .github/dependabot.yml
Labels: ci

#3960 Fix GET /api/proxy with pagination
  jupyterhub/apihandlers/proxy.py
  jupyterhub/tests/test_api.py
Labels: bug
