Repository jupyterhub/jupyterhub, pull requests merged in 2022-07, with the labels that each got.

#3968 pin nbclassic in dev requirements
  dev-requirements.txt
Labels: maintenance

#3958 add correct autocomplete fields for login form
  share/jupyterhub/templates/login.html
Labels: enhancement

#3883 allow HubAuth to be async
  jupyterhub/services/auth.py
Labels: new

#3967 validate proxy.extra_routes
  examples/server-api/jupyterhub_config.py
  jupyterhub/app.py
  jupyterhub/proxy.py
  jupyterhub/tests/test_proxy.py
Labels: bug

#3962 Add ConfigurableHTTPProxy.log_level
  jupyterhub/proxy.py
Labels: new

#3977 unpin nbclassic
  dev-requirements.txt
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/test_singleuser.py
Labels: maintenance

#3978 Increase stacklevel for decorated warnings
  jupyterhub/scopes.py
Labels: maintenance

#3975 Bump Dockerfile base image to 22.04
  Dockerfile
Labels: maintenance

#3976 Require Python 3.7
  .github/workflows/test.yml
  dev-requirements.txt
  jupyterhub/app.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mockservice.py
  jupyterhub/tests/mocksu.py
  jupyterhub/tests/test_singleuser.py
  jupyterhub/user.py
  jupyterhub/utils.py
  pyproject.toml
  setup.py
Labels: api-change

#3974 Avoid deprecated 'IOLoop.current' method
  jupyterhub/app.py
  jupyterhub/tests/conftest.py
Labels: maintenance

#3984 Backport PR #3936 on branch 2.x (admin: Hub is responsible for username validation)
  jsx/src/components/AddUser/AddUser.jsx
  jsx/src/components/AddUser/AddUser.test.js
  jsx/src/components/CreateGroup/CreateGroup.jsx
  share/jupyterhub/static/js/admin-react.js
Labels: bug

#3969 Fix disabling of individual page template announcements
  share/jupyterhub/templates/home.html
  share/jupyterhub/templates/login.html
  share/jupyterhub/templates/logout.html
  share/jupyterhub/templates/spawn.html
Labels: bug
