Repository jupyterhub/jupyterhub, pull requests merged in 2022-10, with the labels that each got.

#4061 Add note about building the docs from Windows
  docs/source/contributing/docs.rst
Labels: documentation

#4063 Fully resolve requested scopes in oauth
  jupyterhub/apihandlers/auth.py
  jupyterhub/oauth/provider.py
  jupyterhub/scopes.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_scopes.py
  jupyterhub/tests/test_services_auth.py
  jupyterhub/tests/test_spawner.py
Labels: bug

#4068 Update setup.rst
  docs/source/contributing/setup.rst
Labels: needs: upstream action, outreachy-dec22

#4071 Improve rbac/roles documentation
  docs/source/rbac/roles.md
Labels: documentation, needs: review, outreachy-dec22

#4079 Improve the documentation about log messages
  docs/source/admin/log-messages.md
Labels: needs: upstream action, outreachy-dec22

#4065 Modification in community channels docs
  docs/source/contributing/community.rst
Labels: documentation, needs: review, outreachy-dec22

#4074 Update index.rst
  docs/source/index.rst
Labels: documentation, needs: upstream action, outreachy-dec22

#4083 updated websecurity.md
  docs/source/reference/websecurity.md
Labels: documentation, needs: upstream action, outreachy-dec22

#4085 Update troubleshooting.md
  docs/source/troubleshooting.md
Labels: documentation, needs: upstream action, outreachy-dec22

#4091 Update config-user-env.md
  docs/source/reference/config-user-env.md
Labels: documentation, outreachy-dec22

#4092 modified announcement README and config.py
  examples/service-announcement/README.md
  examples/service-announcement/jupyterhub_config.py
Labels: needs: review, outreachy-dec22

#4093 fixed some typos and technical terms
  docs/source/rbac/tech-implementation.md
Labels: documentation, outreachy-dec22

#4096 Link reference to github oauth config with jupyter
  docs/source/reference/config-ghoauth.md
Labels: documentation, outreachy-dec22

#4069 Modifications is testing docs
  docs/source/contributing/tests.rst
Labels: documentation, outreachy-dec22

#4089 Update tech-implementation.md
  docs/source/rbac/tech-implementation.md
Labels: documentation, needs: review, outreachy-dec22

#4081 Migrate community channels to markdown, update text
  docs/source/contributing/community.md
  docs/source/contributing/community.rst
Labels: documentation, needs: review, outreachy-dec22

#4088 Grammatical/link fixes in upgrading doc
  docs/source/admin/upgrading.rst
  docs/source/events/index.rst
  docs/source/getting-started/spawners-basics.md
Labels: documentation, outreachy-dec22

#4095 Update config-proxy.md
  docs/source/reference/config-proxy.md
Labels: documentation, outreachy-dec22

#4111 Typo in templates.md
  docs/source/reference/templates.md
Labels: documentation, outreachy-dec22

#4124 Add concrete steps to services-basics
  docs/source/getting-started/services-basics.md
Labels: documentation, outreachy-dec22

#4132 update spawners-basics.md
  docs/source/getting-started/spawners-basics.md
Labels: documentation, outreachy-dec22

#4114 Issue #41 - Documentation reviewed, made concise and beginners friendly, added a JupyterHub image
  docs/source/reference/config-user-env.md
Labels: documentation, outreachy-dec22

#4135 update websecurity.md
  docs/source/reference/websecurity.md
Labels: documentation, outreachy-dec22

#4116 Upgrading.rst (Fix Duplicate statement)
  docs/source/admin/upgrading.rst
Labels: documentation, outreachy-dec22

#4126 Improve clarity in troubleshooting doc
  docs/source/troubleshooting.md
Labels: documentation, outreachy-dec22

#4145 Added text to documentation for more readability
  docs/source/getting-started/config-basics.md
Labels: documentation, outreachy-dec22

#4146 Update to the spawner basic file
  docs/source/getting-started/spawners-basics.md
Labels: documentation, outreachy-dec22

#4147 oauth doc: added punctuations and capitalized words where necessary
  docs/source/reference/oauth.md
Labels: documentation, outreachy-dec22

#4148 update/spawners.md
  docs/source/reference/spawners.md
Labels: documentation, outreachy-dec22

#4090 Restructured Community communication channels file
  docs/source/contributing/community.md
Labels: documentation, needs: review, outreachy-dec22

#4155 Add link to OAuth 2
  docs/source/reference/oauth.md
Labels: documentation, outreachy-dec22

#4098 Proofread and Improve security-basics.rst
  docs/source/getting-started/security-basics.rst
Labels: documentation, needs: upstream action, outreachy-dec22

#4158 fixes in jsx/README.md
  jsx/README.md
Labels: documentation, outreachy-dec22

#4159 Update roadmap.md
  docs/source/contributing/roadmap.md
Labels: documentation, outreachy-dec22

#4161 Improve text in proxy docs
  docs/source/reference/separate-proxy.md
Labels: documentation, outreachy-dec22

#4162 Typo in institutional-faq
  docs/source/getting-started/institutional-faq.md
Labels: documentation, outreachy-dec22

#4160 revise sudo config documentation
  docs/source/reference/config-sudo.md
Labels: documentation, outreachy-dec22

#4154 Remove redundant ref target for roles
  docs/source/rbac/roles.md
Labels: documentation

#4152 Link back to rbac from use-cases
  docs/source/rbac/use-cases.md
Labels: documentation, outreachy-dec22

#4026 Add browser-based tests with Selenium
  .github/workflows/test.yml
  dev-requirements.txt
  jupyterhub/tests/selenium/__init__.py
  jupyterhub/tests/selenium/conftest.py
  jupyterhub/tests/selenium/locators.py
  jupyterhub/tests/selenium/test_browser.py
  pytest.ini
Labels: maintenance

#4153 Consistent capitalization of Authenticator
  docs/source/getting-started/authenticators-users-basics.md
Labels: documentation, outreachy-dec22

#4157 Improve JupyterHub's REST API doc
  docs/source/reference/rest.md
Labels: documentation, outreachy-dec22

#4106 Edited and restructured `server-api` file
  docs/source/reference/server-api.md
Labels: documentation, outreachy-dec22

#4166 Welcome first-time contributors to the forum
  docs/source/contributing/community.md
Labels: documentation, outreachy-dec22

#4169 typo in contributing doc
  docs/source/contributing/docs.rst
Labels: documentation, outreachy-dec22

#4170 Updated deployment gallery links
  docs/source/gallery-jhub-deployments.md
Labels: documentation, outreachy-dec22

#4171 typos in example readme
  examples/bootstrap-script/README.md
Labels: documentation, outreachy-dec22

#4109 Reviewed the documentation
  docs/source/events/index.rst
Labels: documentation, outreachy-dec22

#4168 clarify CHP downsides in proxy doc
  docs/source/reference/proxy.md
Labels: documentation, outreachy-dec22

#4129 reorder REST API doc
  docs/source/reference/rest.md
Labels: documentation, outreachy-dec22

#4173 jsx: remove unused useState
  jsx/src/components/Groups/Groups.jsx
Labels: maintenance, outreachy-dec22

#4140 add link to rbac index from implementation
  docs/source/rbac/tech-implementation.md
Labels: documentation, needs: upstream action, outreachy-dec22

#4113 proofread upgrading docs
  docs/source/admin/upgrading.rst
Labels: documentation, outreachy-dec22
