Repository jupyterhub/jupyterhub, pull requests merged in 2022-09, with the labels that each got.

#4018 reset offset to 0 on name filter change
  jsx/src/Store.js
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
Labels: bug

#4029 Update changelog for 3.0.0
  docs/source/changelog.md
Labels: documentation

#4034 Fix Dockerfile yarn JSX build
  Dockerfile
  dockerfiles/test.py
Labels: bug

#4035 setup.py: require npm, check that NPM CSS JSX commands succeed
  .github/workflows/release.yml
  setup.py
Labels: maintenance
