Repository jupyterhub/jupyterhub, pull requests merged in 2022-03, with the labels that each got.

#3808 Apache: set X-Forwarded-Proto header
  docs/source/reference/config-proxy.md
Labels: documentation

#3809 Add user token to JupyterLab PageConfig
  docs/source/reference/services.md
  jupyterhub/services/auth.py
  jupyterhub/singleuser/mixins.py
Labels: enhancement

#3802 Replace failed spawners when starting new launch
  jupyterhub/apihandlers/users.py
  jupyterhub/handlers/pages.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_pages.py
  jupyterhub/user.py
Labels: bug

#3819 allow Spawner.server to be mocked without underlying orm_spawner
  jupyterhub/spawner.py
  jupyterhub/tests/test_spawner.py
Labels: maintenance

#3823 Fix clearing cookie with custom xsrf cookie options
  jupyterhub/handlers/base.py
Labels: bug

#3822 Fix admin dashboard table sorting
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  share/jupyterhub/static/js/admin-react.js
Labels: bug

#3824 changelog for 2.2.1
  docs/source/changelog.md
Labels: documentation

#3826 ci: standalone jsx workflow and verify compiled asset matches source code
  .github/workflows/test-jsx.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  share/jupyterhub/static/js/admin-react.js
Labels: ci

#3713 allow user-defined custom scopes
  docs/source/rbac/scopes.md
  examples/custom-scopes/grades.py
  examples/custom-scopes/jupyterhub_config.py
  jupyterhub/apihandlers/auth.py
  jupyterhub/app.py
  jupyterhub/scopes.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mockservice.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_scopes.py
  jupyterhub/tests/test_services_auth.py
Labels: new

#3835 remove lingering reference to distutils
  jupyterhub/tests/test_app.py
Labels: maintenance

#3849 The word `used` is duplicated in upgrade.md
  docs/source/rbac/upgrade.md
Labels: documentation
