Repository jupyterhub/jupyterhub, pull requests merged in 2023-09, with the labels that each got.

#4549 Document `oauth_client_id` must start with service-
  examples/external-oauth/README.md
Labels: documentation

#4542 Fix include_stopped_servers in paginated next_url
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/test_api.py
Labels: bug

#4550 Fix external-oauth example jupyterhub_config.py
  examples/external-oauth/jupyterhub_config.py
Labels: documentation

#4558 Remove broken link to BIDS video
  docs/source/reference/gallery-jhub-deployments.md
Labels: documentation

#4556 add some more service credential docs
  docs/source/explanation/oauth.md
  docs/source/reference/services.md
Labels: documentation

#4552 Small fixes to services docs
  docs/source/reference/services.md
Labels: documentation

#4508 Documentation for RTC for JupyterLab >= 4.0
  docs/source/tutorial/collaboration-users.md
Labels: documentation

#4555 fail if external oauth service lacks required oauth_redirect_uri
  jupyterhub/app.py
  jupyterhub/services/service.py
Labels: bug

#4562 Use `user.stop` to cleanup spawners that stopped while Hub was down
  jupyterhub/app.py
Labels: bug

#4560 singleuser extension: persist token from ?token=... url in cookie
  jupyterhub/services/auth.py
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4561 Improve debugging when waiting for servers
  jupyterhub/proxy.py
  jupyterhub/utils.py
Labels: enhancement

#4564 undeprecate JupyterHub.ip/port/base_url
  jupyterhub/app.py
Labels: documentation, maintenance

#4567 Use {base_url}/api for checking hub version
  jupyterhub/objects.py
  jupyterhub/user.py
Labels: bug

#4572 Don't log user model on auth by default
  jupyterhub/services/auth.py
Labels: enhancement

#4511 Rename parameter for post_auth_hook to be clearer
  jupyterhub/auth.py
Labels: documentation

#4570 fix mutation of frozenset in scope intersection
  jupyterhub/scopes.py
  jupyterhub/tests/test_scopes.py
Labels: bug

#4571 TST: apply lower-bound pins during install, rather than later
  .github/workflows/test.yml
  ci/oldest-dependencies/oldest-dependencies.txt
  ci/oldest-dependencies/requirements.in
  ci/oldest-dependencies/requirements.txt
  jupyterhub/tests/extension/__init__.py
  pyproject.toml
Labels: maintenance

#4583 move oldest-dependencies to requirements.old
  .github/workflows/test.yml
  ci/oldest-dependencies/requirements.old
Labels: maintenance

#4586 skip linkcheck for linux.die.net
  docs/source/conf.py
Labels: maintenance
