Repository jupyterhub/jupyterhub, pull requests merged in 2023-12, with the labels that each got.

#4630 avoid setting unused oauth state cookies on API requests
  jupyterhub/services/auth.py
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4645 explicitly require groups in auth model when Authenticator.manage_groups is enabled
  jupyterhub/auth.py
  jupyterhub/handlers/base.py
Labels: breaking

#4651 avoid attempting to patch removed IPythonHandler with notebook v7
  jupyterhub/singleuser/mixins.py
Labels: bug

#4662 docs: Remove non-actionable step from developer setup
  docs/source/contributing/setup.md
Labels: documentation

#4663 temporarily pin pytest-asyncio
  pyproject.toml
Labels: maintenance

#4658 Compare major hub and singleuser versions only
  jupyterhub/_version.py
  jupyterhub/tests/test_version.py
Labels: enhancement
