Repository jupyterhub/jupyterhub, pull requests merged in 2023-02, with the labels that each got.

#4328 Selenium: adding new cases that covered Admin UI page
  jsx/src/util/jhapiUtil.js
  jupyterhub/tests/selenium/test_browser.py
Labels: maintenance

#4319 require sqlalchemy 1.4
  jupyterhub/orm.py
  jupyterhub/tests/test_db.py
  jupyterhub/tests/utils.py
  pytest.ini
  requirements.txt
Labels: breaking

#4348 temporary fix: pin base-notebook tag
  .github/workflows/release.yml
  jupyterhub/tests/selenium/test_browser.py
  singleuser/Dockerfile
Labels: maintenance

#4341 Document use of pytest-asyncio in JupyterHub test suite
  docs/source/contributing/tests.md
Labels: documentation

#4356 avoid logging error when browsers send invalid cookies
  jupyterhub/log.py
Labels: bug

#4354 Make singleuser server-extension default
  .github/workflows/test.yml
  jupyterhub/singleuser/__init__.py
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/test_singleuser.py
  pytest.ini
Labels: new

#4365 admin panel: fix condition for start/stop buttons on user servers
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jupyterhub/tests/selenium/conftest.py
  jupyterhub/tests/selenium/test_browser.py
Labels: bug

#4374 Getting started link broken
  README.md
Labels: documentation

#4363 JupyterHub sphinx theme
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#4377 reduce nested hierarchy in docs organization
  docs/source/explanation/capacity-planning.md
  docs/source/explanation/database.md
  docs/source/explanation/index.md
  docs/source/explanation/oauth.md
  docs/source/explanation/websecurity.md
  docs/source/howto/index.md
  docs/source/redirects.txt
  docs/source/reference/api/app.md
  docs/source/reference/api/auth.md
  docs/source/reference/api/index.md
  docs/source/reference/api/proxy.md
  docs/source/reference/api/service.md
  docs/source/reference/api/services.auth.md
  docs/source/reference/api/spawner.md
  docs/source/reference/api/user.md
  docs/source/reference/authenticators.md
  docs/source/reference/changelog.md
  docs/source/reference/config-reference.md
  docs/source/reference/event-logging.md
  docs/source/reference/gallery-jhub-deployments.md
  docs/source/reference/index.md
  docs/source/reference/monitoring.md
  docs/source/reference/server-actions.md
  docs/source/reference/services.md
  docs/source/reference/spawners.md
  docs/source/reference/technical-overview.md
  docs/source/reference/urls.md
  docs/source/tutorial/index.md
  docs/source/tutorial/installation-basics.md
  docs/source/tutorial/quickstart-docker.md
  docs/source/tutorial/quickstart.md
  docs/source/tutorial/server-api.md
Labels: documentation

#4375 changelog for 4.0 beta
  docs/source/redirects.txt
  docs/source/reference/changelog.md
Labels: documentation
