Repository jupyterhub/jupyterhub, pull requests merged in 2023-08, with the labels that each got.

#4509 Improve Auth module code documentation
  jupyterhub/auth.py
Labels: documentation

#4523 doc: update notebook config URL
  docs/source/howto/configuration/config-user-env.md
Labels: documentation

#4522 document how to use notebook v7 with jupyterhub
  docs/source/howto/configuration/config-user-env.md
  jupyterhub/singleuser/app.py
Labels: documentation

#4516 Add "address already in use" troubleshooting hints
  docs/source/contributing/setup.md
Labels: documentation

#4381 Add REST API for managing services at runtime
  ci/init-db.sh
  docs/source/_static/rest-api.yml
  docs/source/howto/rest.md
  docs/source/reference/services.md
  jupyterhub/alembic/versions/3c2384c5aae1_add_from_config_column_to_the_services_.py
  jupyterhub/alembic/versions/651f5419b74d_api_token_scopes.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/services.py
  jupyterhub/app.py
  jupyterhub/oauth/provider.py
  jupyterhub/orm.py
  jupyterhub/roles.py
  jupyterhub/scopes.py
  jupyterhub/services/service.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_app.py
  jupyterhub/tests/test_db.py
  jupyterhub/tests/test_roles.py
Labels: new

#4530 Backport PR #4491 on branch 4.x (avoid counting failed requests to not-running servers as 'activity')
  jupyterhub/handlers/base.py
Labels: enhancement

#4528 Backport PR #4503 on branch 4.x (set root_dir when using singleuser extension)
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/extension/__init__.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4529 Backport PR #4523 on branch 4.x (doc: update notebook config URL)
  docs/source/howto/configuration/config-user-env.md
Labels: documentation

#4531 Backport PR #4475 on branch 4.x (Allow setting custom log_function in tornado_settings in SingleUserServer)
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
Labels: bug

#4533 Backport PR #4489 on branch 4.x (improve permission-denied errors for various cases)
  jupyterhub/apihandlers/base.py
  jupyterhub/handlers/base.py
  jupyterhub/scopes.py
  jupyterhub/tests/test_api.py
Labels: enhancement

#4534 Changelog for 4.0.2
  docs/source/reference/changelog.md
Labels: documentation

#4535 Backport PR #4534 on branch 4.x (Changelog for 4.0.2)
  docs/source/reference/changelog.md
Labels: documentation

#4494 Improve query performance with eager loading
  jupyterhub/alembic/versions/651f5419b74d_api_token_scopes.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/users.py
  jupyterhub/orm.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_scopes.py
  requirements.txt
Labels: enhancement

#4525 Add `JUPYTERHUB_METRICS_PREFIX` environment variable to customize metrics prefix
  docs/source/reference/monitoring.md
  jupyterhub/metrics.py
  jupyterhub/tests/test_metrics.py
  requirements.txt
Labels: new

#4471 add JupyterHub.subdomain_hook
  jupyterhub/app.py
  jupyterhub/services/service.py
  jupyterhub/tests/test_utils.py
  jupyterhub/user.py
  jupyterhub/utils.py
  requirements.txt
  share/jupyterhub/templates/page.html
Labels: new, breaking

#4536 Mention NomadSpawner
  docs/source/reference/spawners.md
Labels: documentation

#4520 Support Jupyverse as a single-user server
  .github/workflows/test.yml
  jupyterhub/singleuser/__init__.py
  jupyterhub/singleuser/app.py
  jupyterhub/tests/test_singleuser.py
Labels: new
