Repository jupyterhub/jupyterhub, pull requests merged in 2023-03, with the labels that each got.

#4373 add collaboration accounts tutorial
  docs/source/images/collaboration-admin-ui.png
  docs/source/images/jupyterlab-rtc.png
  docs/source/tutorial/collaboration-users.md
  docs/source/tutorial/index.md
  examples/collaboration-accounts/README.md
  examples/collaboration-accounts/jupyterhub_config.py
  examples/collaboration-accounts/projects.yaml
Labels: documentation

#4379 remove pin from singleuser
  singleuser/Dockerfile
Labels: maintenance

#4386 Re-enable links to REST API
  docs/source/conf.py
  docs/source/explanation/database.md
Labels: documentation

#4392 avoid warning on engine_connect listener
  jupyterhub/orm.py
Labels: maintenance

#4390 Add emphasis about role loading and hub restarts.
  docs/source/tutorial/collaboration-users.md
Labels: documentation

#4399 add some more detail and examples to database doc
  .github/workflows/test.yml
  docs/source/explanation/database.md
  jupyterhub/tests/test_db.py
Labels: documentation

#4400 add Spawner.server_token_scopes config
  jupyterhub/roles.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_spawner.py
  jupyterhub/user.py
Labels: new

#4394 Reduce size of jupyterhub image
  .github/workflows/test.yml
  Dockerfile
Labels: maintenance
