Repository jupyterhub/jupyterhub, pull requests merged in 2023-04, with the labels that each got.

#4408 dependabot: fix syntax error of not using quotes for ##:##
  .github/dependabot.yml
Labels: maintenance

#4419 Disable dev traitlets
  .github/workflows/test.yml
Labels: ci

#4417 admin page: improve display of long lists (groups, etc.)
  jsx/package.json
  jsx/src/components/ReactObjectTableViewer/LICENSE
  jsx/src/components/ReactObjectTableViewer/ReactObjectTableViewer.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/server-dashboard.css
  jsx/yarn.lock
Labels: enhancement

#4423 add remaining redirects for docs reorg
  .github/workflows/test-docs.yml
  docs/source/conf.py
  docs/source/redirects.txt
Labels: maintenance

#4424 final changelog for 4.0.0
  docs/source/reference/changelog.md
Labels: documentation

#4427 Fix some public URL links within the docs
  docs/source/contributing/setup.md
  docs/source/faq/institutional-faq.md
  docs/source/faq/troubleshooting.md
  docs/source/reference/changelog.md
Labels: maintenance

#4426 add upgrade note for 4.0 to changelog
  docs/source/reference/changelog.md
Labels: documentation

#4429 docs: fix missing redirects for api to reference/api
  docs/source/redirects.txt
Labels: documentation

#4420 Begin setup of playwright tests
  .github/workflows/test.yml
  jupyterhub/tests/browser/conftest.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/selenium/test_browser.py
  pytest.ini
  setup.py
Labels: maintenance
