Repository jupyterhub/jupyterhub, pull requests merged in 2023-05, with the labels that each got.

#4432 add HUNT into research institutions
  docs/source/faq/institutional-faq.md
Labels: documentation

#4441 Fix "Thanks" typo.
  .github/workflows/support-bot.yml
Labels: documentation

#4444 Remove Dockerfile.alpine
  .github/workflows/test.yml
  dockerfiles/Dockerfile.alpine
  dockerfiles/README.md
Labels: maintenance

#4428 update sharing faq for 2023
  docs/source/conf.py
  docs/source/faq/faq.md
  docs/source/images/shareable_link.webp
Labels: documentation

#4443 Update jsx dependencies as much as possible
  .github/workflows/release.yml
  Dockerfile
  jsx/package.json
  jsx/yarn.lock
Labels: maintenance, ci

#4448 Fix link to collaboration accounts doc in example
  examples/collaboration-accounts/README.md
Labels: maintenance

#4451 preserve CLI > env priority config in jupyterhub-singleuser extension
  jupyterhub/singleuser/extension.py
Labels: bug

#4456 Config reference: link to nicer(?) API docs first
  docs/source/reference/config-reference.md
Labels: documentation

#4454 Add CERN to Gallery of JupyterHub Deployments
  docs/source/reference/gallery-jhub-deployments.md
Labels: documentation

#4458 'servers' should be a dict of dicts, not a list of dicts in rest-api.yml
  docs/source/_static/rest-api.yml
Labels: documentation
