Repository jupyterhub/jupyterhub, pull requests merged in 2023-07, with the labels that each got.

#4476 admin page: buttons handle pending status correctly
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/components/ServerDashboard/server-dashboard.css
  jsx/testing/group.json
  jsx/testing/index.html
  jsx/testing/user.json
  jsx/webpack.config.js
  jsx/yarn.lock
  jupyterhub/tests/browser/test_browser.py
Labels: bug

#4503 set root_dir when using singleuser extension
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/extension/__init__.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4506 typo: defaut->default
  jupyterhub/singleuser/extension.py
Labels: maintenance

#4496 Reduce O(N) queries during startup
  jupyterhub/app.py
Labels: enhancement
