Repository jupyterhub/jupyterhub, pull requests merged in 2023-01, with the labels that each got.

#3651 Dynamic table for changing customizable properties of groups
  docs/source/_static/rest-api.yml
  jsx/src/components/DynamicTable/DynamicTable.jsx
  jsx/src/components/DynamicTable/table-select.css
  jsx/src/components/GroupEdit/GroupEdit.jsx
  jsx/src/util/withAPI.js
  jupyterhub/alembic/versions/0eee8c825d24_added_properties_column.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/groups.py
  jupyterhub/app.py
  jupyterhub/orm.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_app.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_scopes.py
Labels: new

#4295 Fix formatting of load_groups help string
  jupyterhub/app.py
Labels: bug

#4297 docs: fix linkcheck in gallery
  docs/source/conf.py
  docs/source/gallery-jhub-deployments.md
Labels: maintenance

#4298 Selenium testing: adding new case covered the authorisation page
  jupyterhub/tests/selenium/test_browser.py
Labels: maintenance

#4299 test and fix deprecated load_groups list
  jupyterhub/app.py
  jupyterhub/tests/test_app.py
Labels: bug

#4292 expand database docs
  docs/source/reference/database.md
Labels: documentation

#4303 make sure event-schemas are installed
  ci/check_installed_data.py
  setup.py
Labels: bug

#4304 Fix the oauthenticator docs api links
  docs/source/getting-started/authenticators-users-basics.md
Labels: maintenance

#4032 Use XSRF tokens for cross-site checks
  jsx/src/util/jhapiUtil.js
  jupyterhub/apihandlers/auth.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/hub.py
  jupyterhub/apihandlers/users.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/login.py
  jupyterhub/handlers/pages.py
  jupyterhub/log.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_named_servers.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_services_auth.py
  jupyterhub/tests/test_singleuser.py
  jupyterhub/tests/utils.py
  share/jupyterhub/static/js/jhapi.js
  share/jupyterhub/templates/login.html
  share/jupyterhub/templates/oauth.html
  share/jupyterhub/templates/page.html
  share/jupyterhub/templates/spawn.html
Labels: api-change, breaking

#4309 number agreement in authenticators-users-basics
  docs/source/getting-started/authenticators-users-basics.md
Labels: documentation

#4302 sqlalchemy 2 compatibility
  .github/workflows/test.yml
  jupyterhub/apihandlers/groups.py
  jupyterhub/app.py
  jupyterhub/oauth/provider.py
  jupyterhub/orm.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/utils.py
  jupyterhub/user.py
  pytest.ini
Labels: maintenance

#4315 Backport PR #4302: sqlalchemy 2 compatibility
  .github/workflows/test.yml
  jupyterhub/apihandlers/groups.py
  jupyterhub/app.py
  jupyterhub/oauth/provider.py
  jupyterhub/orm.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/utils.py
  jupyterhub/user.py
  pytest.ini
Labels: bug

#4317 Backport PR #4303 on branch 3.x (make sure event-schemas are installed)
  ci/check_installed_data.py
  setup.py
Labels: bug

#4316 changelog for 3.1.1
  docs/source/changelog.md
Labels: documentation

#4318 Backport PR #4316 on branch 3.x (changelog for 3.1.1)
  docs/source/changelog.md
Labels: documentation

#4324 Remove no longer relevant notice in readme
  README.md
Labels: documentation

#4325 pre-commit: bump isort
  .pre-commit-config.yaml
Labels: maintenance

#4327 also ignore sqlite backups
  .gitignore
Labels: maintenance

#4326 Improve contrast on muted text
  share/jupyterhub/static/less/variables.less
Labels: accessibility
