Repository jupyterhub/jupyterhub, pull requests merged in 2023-11, with the labels that each got.

#4628 Include LDAP groups in local spawner gids
  jupyterhub/spawner.py
Labels: enhancement

#4627 doc: Add the include_stopped_server field to the /users/name interface
  docs/source/_static/rest-api.yml
Labels: documentation

#4563 only set 'domain' field on session-id cookie
  jupyterhub/handlers/base.py
Labels: enhancement

#4585 only show links to services users have access to
  jupyterhub/handlers/base.py
  jupyterhub/scopes.py
  jupyterhub/services/service.py
  jupyterhub/tests/test_pages.py
Labels: enhancement

#4578 Improve requests for tokens with scopes
  docs/source/_static/rest-api.yml
  docs/source/howto/rest.md
  docs/source/rbac/scopes.md
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/browser/test_browser.py
  share/jupyterhub/static/js/token.js
  share/jupyterhub/templates/token.html
Labels: new

#4633 Authenticator reference doc: update authenticate return
  docs/source/reference/authenticators.md
Labels: documentation

#4641 Publish to Docker Hub alongside Quay.io
  .github/workflows/release.yml
Labels: maintenance

#4632 simplify, avoid errors in parsing accept headers
  jupyterhub/tests/test_utils.py
  jupyterhub/utils.py
Labels: bug

#4643 add warning when an oauth client is used after its secret is deleted
  jupyterhub/oauth/provider.py
Labels: enhancement

#4644 Log token deletions via API
  jupyterhub/apihandlers/users.py
Labels: enhancement

#4648 add Spawner.poll_jitter
  jupyterhub/spawner.py
Labels: new
