Repository jupyterhub/jupyterhub, pull requests merged in 2023-06, with the labels that each got.

#4463 Reorder token request docs
  docs/source/howto/rest.md
  docs/source/images/token-page.png
  docs/source/images/token-request-success.png
  docs/source/images/token-request.png
  docs/source/tutorial/getting-started/services-basics.md
  share/jupyterhub/templates/token.html
Labels: documentation

#4472 changelog for 4.0.1
  docs/source/reference/changelog.md
Labels: documentation

#4477 Move most package config to declarative pyproject.toml
  MANIFEST.in
  jupyterhub/tests/browser/__init__.py
  pyproject.toml
  setup.py
Labels: maintenance

#4475 Allow setting custom log_function in tornado_settings in SingleUserServer
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
Labels: bug

#4480 Remove check for allowed_users for users created via role or group config
  jupyterhub/app.py
  jupyterhub/tests/test_app.py
Labels: new

#4489 improve permission-denied errors for various cases
  jupyterhub/apihandlers/base.py
  jupyterhub/handlers/base.py
  jupyterhub/scopes.py
  jupyterhub/tests/test_api.py
Labels: enhancement

#4455 Add Spawner.progress_ready_hook for customizing the ready event
  jupyterhub/apihandlers/users.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_api.py
Labels: new

#4491 avoid counting failed requests to not-running servers as 'activity'
  jupyterhub/handlers/base.py
Labels: enhancement

#4492 Add missing param descriptions for `HubAuth`
  jupyterhub/services/auth.py
Labels: documentation

#4497 orm: trade backref for back_populates
  jupyterhub/orm.py
Labels: maintenance

#4498 report db query counts in test output
  jupyterhub/tests/conftest.py
  jupyterhub/tests/mocking.py
Labels: maintenance

#4500 Fix typo in database.md
  docs/source/explanation/database.md
Labels: documentation
