Repository jupyterhub/jupyterhub, pull requests merged in 2024-03, with the labels that each got.

#4717 allow callable values in c.JupyterHub.template_vars
  jupyterhub/app.py
  jupyterhub/handlers/base.py
Labels: new

#4682 Note that you can throw a 403 from authenticator methods
  jupyterhub/auth.py
Labels: documentation

#4721 Implement sort order in GET /users
  docs/source/_static/rest-api.yml
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/test_api.py
Labels: new

#4720 admin: persist page view parameters in url
  .gitignore
  jsx/package-lock.json
  jsx/package.json
  jsx/src/App.jsx
  jsx/src/Store.js
  jsx/src/components/DynamicTable/DynamicTable.jsx
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/PaginationFooter/PaginationFooter.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/util/paginationParams.js
  jsx/webpack.config.js
  jupyterhub/tests/browser/test_browser.py
  setup.py
Labels: new

#4722 server-side sorting of admin page
  jsx/package-lock.json
  jsx/package.json
  jsx/src/components/PaginationFooter/PaginationFooter.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jsx/src/components/ServerDashboard/server-dashboard.css
  jsx/src/util/jhapiUtil.js
  jsx/src/util/paginationParams.js
  jsx/src/util/withAPI.js
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/browser/test_browser.py
Labels: new

#4723 admin: update navigation for react-router v6
  jsx/src/components/AddUser/AddUser.jsx
  jsx/src/components/AddUser/AddUser.test.js
  jsx/src/components/CreateGroup/CreateGroup.jsx
  jsx/src/components/CreateGroup/CreateGroup.test.js
  jsx/src/components/DynamicTable/DynamicTable.jsx
  jsx/src/components/EditUser/EditUser.jsx
  jsx/src/components/EditUser/EditUser.test.js
  jsx/src/components/GroupEdit/GroupEdit.jsx
  jsx/src/components/GroupEdit/GroupEdit.test.jsx
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
Labels: maintenance

#4725 Fix typo in the `rest-api.yml`
  docs/source/_static/rest-api.yml
Labels: documentation

#4724 switch to ruff for lint, format
  .pre-commit-config.yaml
  bower-lite
  demo-image/jupyterhub_config.py
  examples/bootstrap-script/jupyterhub_config.py
  examples/external-oauth/jupyterhub_config.py
  examples/postgres/hub/jupyterhub_config.py
  examples/server-api/start-stop-server.py
  examples/service-announcement/jupyterhub_config.py
  examples/service-fastapi/jupyterhub_config.py
  examples/service-notebook/external/jupyterhub_config.py
  examples/service-notebook/managed/jupyterhub_config.py
  examples/service-whoami-flask/jupyterhub_config.py
  examples/service-whoami-flask/whoami-flask.py
  examples/service-whoami/jupyterhub_config.py
  examples/spawn-form/jupyterhub_config.py
  examples/user-sharing/share-api.ipynb
  jupyterhub/alembic/versions/19c0846f6344_base_revision_for_0_5.py
  jupyterhub/alembic/versions/99a28a4418e1_user_created.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/users.py
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/dbutil.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/objects.py
  jupyterhub/orm.py
  jupyterhub/proxy.py
  jupyterhub/scopes.py
  jupyterhub/singleuser/_disable_user_config.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_named_servers.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_proxy.py
  jupyterhub/traitlets.py
  jupyterhub/user.py
  jupyterhub/utils.py
  pyproject.toml
Labels: maintenance

#4729 services.md: idle-culler does not need admin
  docs/source/reference/services.md
Labels: documentation

#4733 Catch ValueError while waiting for server to be reachable
  jupyterhub/utils.py
Labels: bug

#4734 Backport PR #4733 on branch 4.x (Catch ValueError while waiting for server to be reachable)
  jupyterhub/utils.py
Labels: bug

#4735 Backport PR #4628 on branch 4.x (Include LDAP groups in local spawner gids)
  jupyterhub/spawner.py
Labels: enhancement

#4736 Bump required Python version in contributing setup to 3.8
  docs/source/contributing/setup.md
Labels: documentation

#4738 run browser tests in subdomain
  .github/workflows/test.yml
  jupyterhub/handlers/base.py
  jupyterhub/tests/browser/test_browser.py
Labels: maintenance

#4739 set login cookie if user changed
  jupyterhub/handlers/base.py
Labels: bug

#4741 Consistently use minimum Python version in docs
  README.md
  docs/source/conf.py
  docs/source/contributing/setup.md
  docs/source/tutorial/quickstart.md
Labels: documentation

#4737 avoid duplicate jupyterhub installation for docs
  .github/workflows/test-docs.yml
  .readthedocs.yaml
  docs/requirements.txt
Labels: maintenance

#4745 allow subclasses to override xsrf check
  jupyterhub/services/auth.py
Labels: bug

#4746 changelog for 4.1.1
  docs/source/reference/changelog.md
Labels: documentation

#4747 forward-port changes for 4.1.1
  docs/source/reference/changelog.md
  jupyterhub/services/auth.py
Labels: maintenance

#4750 rework handling of multiple xsrf tokens
  jupyterhub/_xsrf_utils.py
  jupyterhub/handlers/base.py
  jupyterhub/services/auth.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_services_auth.py
Labels: bug

#4751 changelog for 4.1.2
  docs/source/reference/changelog.md
Labels: documentation

#4743 Officially adopt EffVer
  docs/source/reference/changelog.md
Labels: documentation

#4753 respect jupyter-server disable_check_xsrf setting
  jupyterhub/services/auth.py
Labels: bug

#4754 changelog for 4.1.3
  docs/source/reference/changelog.md
Labels: documentation

#4759 avoid xsrf check on navigate GET requests
  jupyterhub/_xsrf_utils.py
  jupyterhub/services/auth.py
  jupyterhub/tests/test_api.py
Labels: bug

#4764 changelog for 4.1.4
  docs/source/reference/changelog.md
Labels: documentation

#4765 forward-port 4.1.4
  docs/source/reference/changelog.md
  jupyterhub/_xsrf_utils.py
  jupyterhub/services/auth.py
  jupyterhub/tests/test_api.py
Labels: maintenance
