Repository jupyterhub/jupyterhub, pull requests merged in 2024-05, with the labels that each got.

#4805 include domain in PrefixRedirectHandler
  jupyterhub/handlers/base.py
  jupyterhub/tests/browser/test_browser.py
Labels: bug

#4806 use os.getgrouplist to check group membership in allowed_groups
  jupyterhub/auth.py
  jupyterhub/tests/test_auth.py
Labels: bug

#4809 docs: fix internal reference typo
  docs/source/reference/services.md
Labels: documentation

#4807 switch from jupyter-telemetry to jupyter-events
  docs/source/conf.py
  docs/source/reference/event-logging.md
  jupyterhub/app.py
  jupyterhub/event-schemas/server-actions/v1.yaml
  jupyterhub/handlers/base.py
  jupyterhub/tests/test_eventlog.py
  requirements.txt
Labels: breaking

#4811 Update changelog for 5.0b2
  docs/source/reference/changelog.md
Labels: documentation

#4812 ci: enable pip cache
  .github/workflows/release.yml
  .github/workflows/test-docs.yml
  .github/workflows/test.yml
Labels: maintenance

#4814 quieter logging in activity-reporting when hub is temporarily unavailable
  jupyterhub/singleuser/extension.py
Labels: enhancement

#4817 add full URLs to share models
  docs/source/_static/rest-api.yml
  docs/source/reference/sharing.md
  docs/source/tutorial/sharing.md
  jupyterhub/apihandlers/shares.py
Labels: enhancement

#4815 admin: don't use state change to update offset
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
Labels: bug

#4820 final changelog for 5.0.0
  docs/source/reference/changelog.md
  docs/source/tutorial/getting-started/security-basics.md
Labels: documentation

#4828 further emphasize that admin_users config only grants permission
  docs/source/tutorial/getting-started/authenticators-users-basics.md
  jupyterhub/auth.py
Labels: documentation

#4829 Fix wording for `read:users` scope description
  docs/source/_static/rest-api.yml
  jupyterhub/scopes.py
Labels: documentation
