Repository jupyterhub/jupyterhub, pull requests merged in 2024-06, with the labels that each got.

#4831 Add token_expires_in_max_seconds configuration
  jupyterhub/apihandlers/users.py
  jupyterhub/app.py
  jupyterhub/handlers/pages.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/test_api.py
  share/jupyterhub/templates/token.html
Labels: new

#4836 fix formatting of group_overrides docstring
  jupyterhub/spawner.py
Labels: documentation

#4835 reduce cost of event_loop_interval metric
  docs/source/reference/monitoring.md
  jupyterhub/metrics.py
Labels: enhancement

#2726 Jupyter(Hub) conceptual intro
  docs/source/explanation/concepts.md
  docs/source/explanation/index.md
  docs/source/explanation/singleuser.md
  docs/source/faq/troubleshooting.md
  docs/source/reference/services.md
  docs/source/tutorial/getting-started/services-basics.md
Labels: documentation

#4837 Provide consistent myst references to documentation pages - part 1
  docs/source/contributing/community.md
  docs/source/contributing/contributor-list.md
  docs/source/contributing/docs.md
  docs/source/contributing/index.md
  docs/source/contributing/roadmap.md
  docs/source/contributing/security.md
  docs/source/contributing/setup.md
  docs/source/contributing/tests.md
  docs/source/explanation/capacity-planning.md
  docs/source/explanation/concepts.md
  docs/source/explanation/database.md
  docs/source/explanation/index.md
  docs/source/explanation/oauth.md
  docs/source/explanation/singleuser.md
  docs/source/explanation/websecurity.md
  docs/source/faq/faq.md
  docs/source/faq/institutional-faq.md
  docs/source/faq/troubleshooting.md
  docs/source/howto/api-only.md
  docs/source/howto/configuration/config-ghoauth.md
  docs/source/howto/configuration/config-proxy.md
  docs/source/howto/configuration/config-sudo.md
  docs/source/howto/configuration/config-user-env.md
  docs/source/howto/log-messages.md
  docs/source/howto/proxy.md
  docs/source/howto/rest.md
  docs/source/howto/separate-proxy.md
  docs/source/howto/templates.md
  docs/source/howto/upgrading-v5.md
  docs/source/howto/upgrading.md
  docs/source/rbac/scopes.md
  docs/source/rbac/upgrade.md
  docs/source/reference/api/index.md
  docs/source/reference/changelog.md
  docs/source/reference/services.md
  docs/source/reference/urls.md
  docs/source/tutorial/getting-started/config-basics.md
  docs/source/tutorial/getting-started/security-basics.md
  docs/source/tutorial/server-api.md
Labels: documentation
