Repository jupyterhub/jupyterhub, pull requests merged in 2024-09, with the labels that each got.

#4897 add dark mode toggle
  share/jupyterhub/static/js/darkmode.js
  share/jupyterhub/static/scss/page.scss
  share/jupyterhub/templates/page.html
Labels: new

#4906 browser tests: use text_content instead of inner_text
  jupyterhub/tests/browser/test_browser.py
Labels: maintenance

#4913 Fix incorrect rounding function
  jupyterhub/handlers/base.py
Labels: bug
