Repository jupyterhub/jupyterhub, pull requests merged in 2024-04, with the labels that each got.

#4769 Fix typo in docstring about Authenticator.blocked_users
  jupyterhub/auth.py
Labels: documentation

#4771 singleuser mixin: include check_xsrf_cookie in overrides
  jupyterhub/singleuser/mixins.py
Labels: bug

#4773 changelog for 4.1.5
  docs/source/reference/changelog.md
Labels: documentation

#4776 forward-port 4.1.5
  docs/source/reference/changelog.md
  jupyterhub/singleuser/mixins.py
Labels: maintenance

#4779 Support forbidding unauthenticated access (`allow_unauthenticated_access = False`)
  jupyterhub/singleuser/_decorator.py
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/test_singleuser.py
Labels: enhancement

#4783 Token UI: move button to after form fields
  share/jupyterhub/templates/token.html
Labels: enhancement

#4782 test: avoid producing '[group]' string in output
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_shares.py
Labels: maintenance

#4701 Add Authenticator config `allow_all` and `allow_existing_users`
  docs/source/reference/authenticators.md
  docs/source/tutorial/getting-started/authenticators-users-basics.md
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_app.py
  jupyterhub/tests/test_auth.py
Labels: new

#4748 Add authenticator-managed roles (`manage_roles`)
  docs/source/reference/authenticators.md
  jupyterhub/alembic/versions/4621fec11365_manage_roles.py
  jupyterhub/alembic/versions/651f5419b74d_api_token_scopes.py
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/handlers/base.py
  jupyterhub/orm.py
  jupyterhub/roles.py
  jupyterhub/scopes.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_auth.py
  jupyterhub/tests/test_db.py
  jupyterhub/tests/test_roles.py
  jupyterhub/user.py
Labels: new

#4790 add token_id to `/api/user`
  docs/source/_static/rest-api.yml
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/test_api.py
Labels: new

#4774 update bootstrap to v5
  .gitignore
  docs/source/contributing/setup.md
  jsx/.gitignore
  jsx/src/components/AddUser/AddUser.jsx
  jsx/src/components/CreateGroup/CreateGroup.jsx
  jsx/src/components/DynamicTable/DynamicTable.jsx
  jsx/src/components/DynamicTable/table-select.css
  jsx/src/components/EditUser/EditUser.jsx
  jsx/src/components/GroupEdit/GroupEdit.jsx
  jsx/src/components/GroupSelect/GroupSelect.jsx
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/PaginationFooter/PaginationFooter.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/server-dashboard.css
  jsx/src/util/error.jsx
  jsx/src/util/layout.jsx
  jupyterhub/handlers/static.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/browser/test_share.py
  jupyterhub/tests/test_pages.py
  package-lock.json
  package.json
  setup.py
  share/jupyterhub/static/js/utils.js
  share/jupyterhub/static/less/style.less
  share/jupyterhub/static/less/variables.less
  share/jupyterhub/static/scss/admin.scss
  share/jupyterhub/static/scss/cssvariables.css
  share/jupyterhub/static/scss/error.scss
  share/jupyterhub/static/scss/login.scss
  share/jupyterhub/static/scss/page.scss
  share/jupyterhub/static/scss/style.scss
  share/jupyterhub/static/scss/variables.scss
  share/jupyterhub/templates/accept-share.html
  share/jupyterhub/templates/admin.html
  share/jupyterhub/templates/home.html
  share/jupyterhub/templates/login.html
  share/jupyterhub/templates/oauth.html
  share/jupyterhub/templates/page.html
  share/jupyterhub/templates/spawn.html
  share/jupyterhub/templates/spawn_pending.html
  share/jupyterhub/templates/token.html
  testing/jupyterhub_config.py
Labels: breaking

#4784 doc: list/get token response is different from post
  docs/source/_static/rest-api.yml
Labels: documentation

#4793 adopt djlint linter/autoformatter for jinja templates
  .pre-commit-config.yaml
  docs/source/_templates/redoc.html
  examples/service-announcement/templates/page.html
  jsx/testing/index.html
  jupyterhub/singleuser/templates/page.html
  pyproject.toml
  share/jupyterhub/templates/404.html
  share/jupyterhub/templates/accept-share.html
  share/jupyterhub/templates/admin.html
  share/jupyterhub/templates/error.html
  share/jupyterhub/templates/home.html
  share/jupyterhub/templates/login.html
  share/jupyterhub/templates/logout.html
  share/jupyterhub/templates/not_running.html
  share/jupyterhub/templates/oauth.html
  share/jupyterhub/templates/page.html
  share/jupyterhub/templates/spawn.html
  share/jupyterhub/templates/spawn_pending.html
  share/jupyterhub/templates/stop_pending.html
  share/jupyterhub/templates/token.html
Labels: maintenance

#4795 increase docker build timeout to 30 minutes
  .github/workflows/release.yml
Labels: maintenance

#4794 Fix counts on list users queries
  jupyterhub/apihandlers/users.py
  jupyterhub/tests/test_api.py
Labels: bug

#4792 changelog for 5.0, add migration doc
  docs/source/explanation/websecurity.md
  docs/source/howto/upgrading-v5.md
  docs/source/howto/upgrading.md
  docs/source/reference/changelog.md
Labels: documentation

#4796 Fix rest API djlint auto-formatting
  .pre-commit-config.yaml
  docs/source/_templates/redoc.html
Labels: documentation

#4797 403 instead of redirect for token-only HubAuth
  examples/service-whoami/jupyterhub_config.py
  jupyterhub/services/auth.py
  jupyterhub/tests/test_services_auth.py
Labels: bug

#4798 add full_url, full_progress_url to server models
  docs/source/_static/rest-api.yml
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/test_named_servers.py
Labels: new

#4799 Relax dependency on async_generator
  jupyterhub/apihandlers/users.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_services.py
  jupyterhub/tests/test_utils.py
  jupyterhub/utils.py
  requirements.txt
Labels: maintenance

#4804 document conditions for oauth_redirect_url more clearly
  jupyterhub/services/service.py
Labels: documentation
