Repository jupyterhub/jupyterhub, pull requests merged in 2024-01, with the labels that each got.

#4665 avoid deprecated datetime.utcnow
  jupyterhub/alembic/versions/99a28a4418e1_user_created.py
  jupyterhub/apihandlers/auth.py
  jupyterhub/apihandlers/users.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/orm.py
  jupyterhub/tests/populate_db.py
  jupyterhub/tests/test_api.py
  jupyterhub/tests/test_orm.py
  jupyterhub/user.py
  jupyterhub/utils.py
Labels: maintenance

#4671 use $http_host in nginx proxy header
  docs/source/howto/configuration/config-proxy.md
Labels: documentation

#4678 pre_spawn_hook doc: make example generic to all spawners
  jupyterhub/spawner.py
Labels: documentation

#4479 add JupyterHub.public_url config
  docs/source/conf.py
  docs/source/reference/services.md
  docs/source/reference/spawners.md
  jupyterhub/apihandlers/auth.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/services/auth.py
  jupyterhub/spawner.py
  jupyterhub/tests/test_user.py
  jupyterhub/user.py
Labels: new

#4677 Improve validation, docs for token.expires_in
  docs/source/_static/rest-api.yml
  jupyterhub/apihandlers/users.py
  jupyterhub/orm.py
Labels: bug

#4676 Add appropriate scope in examples/service-whoami-flask
  examples/service-whoami-flask/README.md
  examples/service-whoami-flask/jupyterhub_config.py
  examples/service-whoami-flask/whoami-flask.py
Labels: documentation

#4608 move service oauth state from cookies to memory
  jupyterhub/services/auth.py
  jupyterhub/tests/test_services_auth.py
Labels: enhancement

#4683 don't run check_allowed until after check_blocked_users resolves
  jupyterhub/auth.py
Labels: maintenance

#4684 enable log capture in pytest, compatibility with pytest 8
  jupyterhub/app.py
  jupyterhub/tests/mocking.py
  jupyterhub/tests/test_proxy.py
  jupyterhub/tests/test_roles.py
Labels: maintenance
