Repository jupyterhub/jupyterhub, pull requests merged in 2024-07, with the labels that each got.

#4860 Pass `kwargs` down to `initialize()` call of the server
  jupyterhub/singleuser/mixins.py
Labels: bug

#4856 Show insecure login warning when not in a secure context
  share/jupyterhub/templates/login.html
Labels: enhancement

#4848 changelog for 5.1.0
  docs/source/reference/changelog.md
Labels: documentation
