Repository jupyterhub/jupyterhub, pull requests merged in 2024-08, with the labels that each got.

#4863 Add PAMAuthenticator.executor_threads configurable, increase default to 4
  jupyterhub/auth.py
Labels: enhancement

#4864 singleuser: fix shutdown mixin
  jupyterhub/singleuser/mixins.py
Labels: bug

#4664 unpin pytest-asyncio
  .github/workflows/test.yml
  jupyterhub/tests/conftest.py
  pyproject.toml
  pytest.ini
Labels: maintenance

#4867 Admin pages: use inherited base_url from render_template
  jsx/src/util/jhapiUtil.js
  jupyterhub/handlers/pages.py
Labels: bug

#4868 bump require.js
  package-lock.json
Labels: maintenance

#4870 start metrics collector in start
  jupyterhub/app.py
Labels: maintenance

#4865 Revoke all permissions from Authenticator.blocked_users
  jupyterhub/app.py
  jupyterhub/auth.py
  jupyterhub/orm.py
  jupyterhub/tests/test_app.py
Labels: new

#4869 add dependabot config for npm
  .github/dependabot.yaml
Labels: ci

#4876 fix python3 -m jupyterhub.app
  jupyterhub/app.py
Labels: bug

#4883 docs: remove some outdated links
  docs/source/faq/troubleshooting.md
  docs/source/reference/gallery-jhub-deployments.md
Labels: documentation

#4882 only group minor dependencies in dependabot
  .github/dependabot.yaml
Labels: maintenance

#4884 update-types typo in dependabot.yml
  .github/dependabot.yaml
Labels: maintenance

#4896 add University of Portland to sample orgs
  docs/source/faq/institutional-faq.md
Labels: documentation
