Repository jupyterhub/jupyterhub, pull requests merged in 2024-02, with the labels that each got.

#4694 Backport PR #4618 on branch 4.x (browser test: wait for token request to finish before reloading)
  jupyterhub/tests/browser/test_browser.py
Labels: maintenance

#4695 Backport PR #4617: try to improve reliability of test_external_proxy
  jupyterhub/tests/test_proxy.py
  setup.py
Labels: maintenance

#4688 Backport PR #4651 on branch 4.x (avoid attempting to patch removed IPythonHandler with notebook v7)
  jupyterhub/singleuser/mixins.py
Labels: bug

#4690 Backport PR #4562 on branch 4.x (Use `user.stop` to cleanup spawners that stopped while Hub was down)
  jupyterhub/app.py
Labels: bug

#4691 Backport PR #4570 on branch 4.x (fix mutation of frozenset in scope intersection)
  jupyterhub/scopes.py
  jupyterhub/tests/test_scopes.py
Labels: bug

#4697 Backport PR #4630: avoid setting unused oauth state cookies on API requests
  jupyterhub/services/auth.py
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4696 Backport PR #4632: simplify, avoid errors in parsing accept headers
  jupyterhub/tests/test_utils.py
  jupyterhub/utils.py
Labels: bug

#4698 Backport quay.io publishing
  .github/workflows/release.yml
  Dockerfile
  README.md
  demo-image/Dockerfile
  docs/source/faq/troubleshooting.md
  docs/source/howto/separate-proxy.md
  docs/source/tutorial/quickstart-docker.md
  examples/service-fastapi/Dockerfile
  onbuild/Dockerfile
  onbuild/README.md
  singleuser/Dockerfile
Labels: maintenance

#4689 Backport PR #4542 on branch 4.x (Fix include_stopped_servers in paginated next_url)
  jupyterhub/apihandlers/base.py
  jupyterhub/tests/test_api.py
Labels: bug

#4687 Backport PR #4560 on branch 4.x (singleuser extension: persist token from ?token=... url in cookie)
  jupyterhub/services/auth.py
  jupyterhub/singleuser/extension.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4594 user-initiated sharing
  .gitignore
  docs/source/_static/rest-api.yml
  docs/source/images/sharing-token.png
  docs/source/rbac/scopes.md
  docs/source/reference/index.md
  docs/source/reference/services.md
  docs/source/reference/sharing.md
  docs/source/tutorial/index.md
  docs/source/tutorial/sharing.md
  examples/user-sharing/README.md
  examples/user-sharing/jupyterhub_config.py
  examples/user-sharing/share-api.ipynb
  examples/user-sharing/share-jupyterlab.ipynb
  jupyterhub/apihandlers/__init__.py
  jupyterhub/apihandlers/base.py
  jupyterhub/apihandlers/shares.py
  jupyterhub/app.py
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/orm.py
  jupyterhub/roles.py
  jupyterhub/scopes.py
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/browser/test_share.py
  jupyterhub/tests/conftest.py
  jupyterhub/tests/test_named_servers.py
  jupyterhub/tests/test_orm.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_roles.py
  jupyterhub/tests/test_scopes.py
  jupyterhub/tests/test_shares.py
  jupyterhub/tests/test_spawner.py
  requirements.txt
  share/jupyterhub/templates/accept-share.html
Labels: new

#4703 test Python 3.12
  .github/workflows/test.yml
Labels: maintenance

#4704 bump pythons, base images on CI
  .github/workflows/release.yml
  .github/workflows/test-docs.yml
  .github/workflows/test-jsx.yml
  .github/workflows/test.yml
  .readthedocs.yaml
Labels: maintenance

#4679 Unescape jinja username
  jupyterhub/tests/browser/conftest.py
  jupyterhub/tests/browser/test_browser.py
  share/jupyterhub/templates/page.html
Labels: bug

#4705 Backport PR #4679 on branch 4.x (Unescape jinja username)
  jupyterhub/tests/browser/__init__.py
  jupyterhub/tests/browser/conftest.py
  jupyterhub/tests/browser/test_browser.py
  share/jupyterhub/templates/page.html
Labels: bug

#4706 Update allowed_users docstring
  jupyterhub/auth.py
Labels: documentation

#4712 Update `black.target_version` in `pyproject.toml`
  pyproject.toml
Labels: maintenance

#4708 Minor broken docs: reference to wiki removed, #4653 fixed
  docs/source/reference/spawners.md
Labels: documentation

#4707 Backport PR #4563 on branch 4.x (only set 'domain' field on session-id cookie)
  jupyterhub/handlers/base.py
Labels: enhancement

#4713 resolve paths in disable_user_config
  jupyterhub/singleuser/_disable_user_config.py
  jupyterhub/tests/test_singleuser.py
Labels: bug

#4714 Backport PR #4561 on branch 4.x (Improve debugging when waiting for servers)
  jupyterhub/proxy.py
  jupyterhub/utils.py
Labels: enhancement
