Repository jupyterhub/jupyterhub, pull requests merged in 2025-03, with the labels that each got.

#5011 raise spawn error if spawn failed while polling
  jupyterhub/handlers/base.py
Labels: bug

#4991 Add $JUPYTERHUB_XSRF_ANONYMOUS_{IP_CIDRS|HEADERS} config for managing anonymous xsrf ids
  docs/source/faq/troubleshooting.md
  jupyterhub/_xsrf_utils.py
Labels: new

#5004 allow group management API when managed_groups is True
  docs/source/reference/authenticators.md
  jupyterhub/apihandlers/groups.py
  jupyterhub/tests/test_api.py
Labels: new

#4967 Allow configuration of bucket sizes in metrics - #4833
  docs/source/reference/monitoring.md
  jupyterhub/metrics.py
Labels: new

#5021 add some debugging output for intermittent share code failure
  jupyterhub/orm.py
  jupyterhub/tests/test_shares.py
Labels: maintenance

#4950 Fixed code formatting for implicit_spawn_seconds (#4949)
  share/jupyterhub/templates/not_running.html
Labels: bug

#5020 make sure custom error messages are shown on regular error pages
  jupyterhub/handlers/base.py
  jupyterhub/handlers/pages.py
  jupyterhub/tests/test_pages.py
  share/jupyterhub/templates/error.html
Labels: bug

#5024 stop publishing images from jupyterhub/jupyterhub
  .github/workflows/registry-overviews.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  demo-image/Dockerfile
  demo-image/README.md
  demo-image/jupyterhub_config.py
  dockerfiles/test.py
  onbuild/Dockerfile
  onbuild/README.md
  singleuser/Dockerfile
  singleuser/README.md
  singleuser/install_jupyterhub
Labels: maintenance

#5025 Try to improve admin paging consistency
  jsx/src/components/Groups/Groups.jsx
  jsx/src/components/Groups/Groups.test.js
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.test.js
  jupyterhub/tests/browser/test_browser.py
Labels: bug

#5023 try to fix flaky spawn_pending browser test
  jupyterhub/tests/browser/test_browser.py
  pytest.ini
Labels: maintenance

#5036 skip js build on readthedocs
  .readthedocs.yaml
  setup.py
Labels: maintenance

#4988 More IPv6: Use bare IPv6 for configuration, use `[ipv6]` when displaying IPv6 outputs
  jupyterhub/app.py
  jupyterhub/objects.py
  jupyterhub/orm.py
  jupyterhub/services/service.py
  jupyterhub/spawner.py
  jupyterhub/utils.py
Labels: enhancement

#5033 url_path_join: handle empty trailing components
  jupyterhub/app.py
  jupyterhub/tests/test_utils.py
  jupyterhub/user.py
  jupyterhub/utils.py
Labels: bug

#5022 improve xsrf errors on login
  jupyterhub/_xsrf_utils.py
  jupyterhub/handlers/login.py
  jupyterhub/tests/browser/test_browser.py
  jupyterhub/tests/test_pages.py
  jupyterhub/tests/test_singleuser.py
  share/jupyterhub/templates/login.html
Labels: enhancement
