Repository jupyterhub/jupyterhub, pull requests merged in 2025-04, with the labels that each got.

#5012 add apply_user_options hook
  docs/source/reference/api/spawner.md
  docs/source/reference/spawners.md
  jupyterhub/spawner.py
  jupyterhub/tests/test_spawner.py
  jupyterhub/user.py
Labels: new

#5037 Add SharedPasswordAuthenticator
  docs/source/reference/api/auth.md
  docs/source/reference/authenticators.md
  jupyterhub/auth.py
  jupyterhub/authenticators/__init__.py
  jupyterhub/authenticators/shared.py
  jupyterhub/tests/test_dummyauth.py
  jupyterhub/tests/test_shared_password.py
  pyproject.toml
Labels: new

#5030 jsx: update and address eslint
  .pre-commit-config.yaml
  jsx/.eslintrc.json
  jsx/eslint.config.mjs
  jsx/package-lock.json
  jsx/package.json
  jsx/src/components/AddUser/AddUser.test.js
  jsx/src/components/GroupEdit/GroupEdit.jsx
  jsx/src/components/ServerDashboard/ServerDashboard.jsx
  jsx/src/util/jhapiUtil.js
  package.json
Labels: maintenance

#5042 changelog for 5.3.0 (RC)
  docs/source/reference/changelog.md
Labels: documentation

#5045 Allow configuration of stop duration metric buckets
  docs/source/reference/monitoring.md
  jupyterhub/metrics.py
Labels: new

#5047 Fix outdated GitHub Wiki links in documentation
  README.md
  docs/source/explanation/concepts.md
  docs/source/howto/configuration/config-sudo.md
  docs/source/tutorial/quickstart.md
Labels: documentation

#5049 set default permissions on workflows
  .github/workflows/release.yml
  .github/workflows/test-docs.yml
Labels: maintenance

#5051 npm audit fix
  jsx/package-lock.json
Labels: dependencies

#5048 changelog for 5.3.0
  docs/source/reference/changelog.md
  docs/source/reference/monitoring.md
  docs/source/reference/spawners.md
Labels: documentation

#5052 doc: spawner.delete_forever applies to users and named servers
  jupyterhub/spawner.py
Labels: documentation

#5056 add forced login example
  docs/source/howto/forced-login.md
  docs/source/howto/index.md
  examples/forced-login/README.md
  examples/forced-login/external_app.py
  examples/forced-login/index.html
  examples/forced-login/jupyterhub_config.py
  examples/forced-login/requirements.txt
Labels: documentation
