Repository jupyterhub/jupyterhub, pull requests merged in 2025-01, with the labels that each got.

#4964 Update `load_groups` config in collaboration-users.md
  docs/source/tutorial/collaboration-users.md
Labels: documentation

#4978 Missing breaking change in 5.0.0 changelog: URL tokens
  docs/source/reference/changelog.md
Labels: documentation

#4968 Fix bug in `GroupEdit`: Users being reset when clicking the button to edit a group
  jsx/src/components/GroupEdit/GroupEdit.jsx
Labels: bug

#4982 make insecure-login-warning visible in dark mode
  share/jupyterhub/static/scss/login.scss
  share/jupyterhub/templates/login.html
Labels: bug, accessibility

#4984 close tornado FDs without closing asyncio loop
  jupyterhub/tests/conftest.py
Labels: maintenance

#4986 Singleuser: listen on IPv4 and IPv6 if ip==""
  jupyterhub/singleuser/extension.py
  jupyterhub/singleuser/mixins.py
Labels: bug

#4990 don't install unused browsers for playwright
  .github/workflows/test.yml
Labels: maintenance
